name: Build
on:
  pull_request:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: docs/example-action@b16d2601a6b948e2fb26f3772276581f31daa7cd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
